# Generated by Django 4.1.4 on 2023-05-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lights', '0004_broker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='keepAlive',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='user',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
